### ISSUE TITLE
Splash Page

### ISSUE THREAD

**Issue by ryanatk** [ryanatk/junction#1]
Create a Splash page with some "Coming Soon!" messaging for customers

### Timeline

ASAP

### Open Questions

1. Besides the Junction logo, is there any other content or messaging we want to display?
1. Do we want to collect email addresses for future announcements? (i.e., Grand Opening)

### Deliverable

Initial customer-facing page with proper content. Future updates & revisions will be done outside the scope of this issue.

**Comment by mishmosh525** [comment]
1. Logo and a "coming soon" should suffice for now. I have a photographer coming out this week to give us some preliminary photography (more macro shots of decor since the space is still somewhat rough around the edges), so if we could incorporate a photo reel like on the sample webpage will references with those, that would be great.

2. If there is a simple way to have these collect in a database, yes. I don't want to get bogged down with updating files though. I imagine the former is pretty simple.

Attached are some food/bev photos that may be helpful placeholders for the short-term.
![livelikejerry-benifit-thelocal-2014w00035](https://cloud.githubusercontent.com/assets/23462328/20281799/ebe8316a-aa7f-11e6-82a7-8c7ef55ca0f8.jpg)
![livelikejerry-benifit-thelocal-2014w00020](https://cloud.githubusercontent.com/assets/23462328/20281811/f64a3590-aa7f-11e6-8d2c-84d50a2ad14a.jpg)
![livelikejerry-benifit-thelocal-2014w00006](https://cloud.githubusercontent.com/assets/23462328/20281819/00396fb2-aa80-11e6-83f2-bccd8bca4122.jpg)
![livelikejerry-benifit-thelocal-2014w00002](https://cloud.githubusercontent.com/assets/23462328/20281827/0639efcc-aa80-11e6-99ac-7b68b5a5ec50.jpg)





![livelikejerry-benifit-thelocal-event2014w00082](https://cloud.githubusercontent.com/assets/23462328/20281713/911f33b4-aa7f-11e6-984f-87343ffb53dd.jpg)
![livelikejerry-benifit-thelocal-event2014w00074](https://cloud.githubusercontent.com/assets/23462328/20281733/a83e747e-aa7f-11e6-92f2-6c9c4aa00a32.jpg)
![livelikejerry-benifit-thelocal-event2014w00057](https://cloud.githubusercontent.com/assets/23462328/20281741/b0983a9c-aa7f-11e6-8cc0-81fc70be0ac6.jpg)
![livelikejerry-benifit-thelocal-2014w00044]
![livelikejerry-benifit-thelocal-2014w00037](https://cloud.githubusercontent.com/assets/23462328/20281783/d5e05334-aa7f-11e6-8fa1-a54966850af8.jpg)
(https://cloud.githubusercontent.com/assets/23462328/20281773/ccdbb238-aa7f-11e6-87f6-769211db35ff.jpg)
![livelikejerry-benifit-thelocal-2014w00047](https://cloud.githubusercontent.com/assets/23462328/20281768/c7c573ba-aa7f-11e6-92e6-5fc3f24069a8.jpg)

**Comment by ryanatk** [comment]
👍

**Comment by ryanatk** [comment]
I've put together a "coming soon" page
https://ryanatk.github.io/junction/coming-soon.html

Notables:

- it looks good on the phone & desktop
- clicking on the phone number prompts the user to call
- I've included a link to the junction facebook page, in lieu of an email sign up

I'm happy to set up a real email signup form ([mailchimp](https://mailchimp.com/pricing/entrepreneur/) is a leader in this space, and free), but unless you have plans to send mass marketing emails, this feels like overkill. And because you'll announce "daily specials" and "events" on the facebook page, facebook appears to be the better option.

Please let me know if you have any feedback or requests, and I can make those changes ASAP

Once we like what's there, we can point your domain name (www.junctionva.com) at this page

**Comment by mishmosh525** [comment]
This looks good to me. Can we add some photos when we have them? Just a rotation or some sort would be great.

When we point the domain, can I have you give more specific instructions? I am familiar with how to forward an address, just want to make sure that is correct, or if I need to do something else.

Thanks!

**Comment by ryanatk** [comment]
### Photos
I can definitely add those when we have them, no problem

### Pointing your domain
I found some [decent instructions online](http://andrewsturges.com/blog/jekyll/tutorial/2014/11/06/github-and-godaddy.html#3-go-to-godaddy-com-and-set-up-two-records). You'll do steps 3-5 (I'm happy to talk you thru it on the phone). Once that's done, I'll complete step #2.

### Facebook instead of emails
Just confirming that we're good with the decision to only include a link to your Facebook page, and not email collection

### Meeting
I'm meeting with Will next week, likely on Tuesday

**Comment by mishmosh525** [comment]
For the pointing... I used the ip address listed on the instructions, should it be different? Also when adding the CNAME, when I put in your web address it gives me this error: "Enter either @ or a valid host name such as: "subdomain.domain.tld""

I've tried no http, no .html, not sure what else to adjust to make it like the link.
![capture](https://cloud.githubusercontent.com/assets/23462328/20633259/84bcc0aa-b312-11e6-8084-a67f2fa2681f.JPG)

**Comment by ryanatk** [comment]
hi @mishmosh525 

i think you just want that to say `ryanatk.github.io`, and github should handle it from there

**Comment by ryanatk** [comment]
i've updated our "coming soon" page to include the images i got from Will
https://ryanatk.github.io/junction/coming-soon.html

I also updated the colors using the "color key" y'all used for paint
https://github.com/ryanatk/junction/blob/master/docs/color-key.md

Please let me know if you have any feedback. I still have a bit of testing and cleanup to do, and I'd like to complete this page this week.

Also, I admit that choosing colors is not my strong point (my wife is a graphic designer, and she agrees). By trade, I focus more on making the site usable & accessible (variety of devices, disabilities, etc), including layout, flexibility, and performance. This is all to say: if you have opinions and preferences for colors, I'm all ears. I'll give you feedback (especially if i think it effects accessibility), but ultimately I want you to be happy with the look & feel.

**Comment by ryanatk** [comment]
this is live
http://www.junctionva.com/coming-soon.html
