### ISSUE TITLE
Pop up calendar when client submits an event form?

### ISSUE THREAD

**Issue by RiceBarrel** [ryanatk/junction#9]
Is it possible to have a calendar pop up where they select a date rather than typing it in? More idiot proof, Michelle says people enter the wrong date all the time.

**Comment by ryanatk** [comment]
i'll look into this

**Comment by ryanatk** [comment]
i've got a solution in place
https://www.junctionva.com/contact-us/

it's not perfect, but it's the best available option:

1. it works on mobile and desktop
1. it uses the native browser datepicker, so this will inherit any improvements made by browsers

i tried the most stable options designed for the desktop, and they all had trouble because of the "popover" nature of the forms. also they were awful on mobile.

here is a screenshot of the interaction (the calendar pops up when you click the arrow on the right) in the chrome browser on a mac
<img width="700" alt="screen shot 2017-01-09 at 10 15 26 am" src="https://cloud.githubusercontent.com/assets/156617/21777600/5c29bdb8-d654-11e6-89ab-db9463ba1294.png">

and here is what it looks like on an iphone
![img_0361](https://cloud.githubusercontent.com/assets/156617/21778384/148522e6-d658-11e6-90b6-11bdd35172b7.PNG)

are we happy with this solution?

**Comment by RiceBarrel** [comment]
I think it works great, thanks Ryan.
